apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-app  # This should match the app label in the deployment
  template:
    metadata:
      labels:
        app: registration-app  # This should also match the app label in the service selector
    spec:
      containers:
        - name: registration-app
          image: registration-app:latest  # Ensure this image exists in your local Minikube environment
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  type: NodePort
  selector:
    app: registration-app  # Match this label to the deployment's label
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
